name: 'Prepare Artifacts'
description: 'Prepare Artifacts'
inputs:
  version:  # id of input
    description: 'version'
    required: true
runs:
  using: "composite"
  steps:
    - name: Print Version
      shell: bash
      run: |
        echo Version is ${{ inputs.version }}.
        echo "Output of Ref is: ${{github.ref}}"