# Reusable step to build a flex template.
name: 'Flex Template'
description: 'Build Flex Template'
inputs:
  version:  # id of input
    description: 'version'
    required: true
runs:
  using: "composite"
  steps:
    - name: Do Some Job
      shell: bash
      run: |
        echo Version is ${{ inputs.version }}.
        echo "Output of Ref is: ${{github.ref}}"