# Reusable step to build and push images.
name: 'Push Images'
description: 'Push Images'
inputs:
  version:  # id of input
    description: 'version'
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: '8'
    - name: Do Some Job
      shell: bash
      run: |
        echo Version is ${{ inputs.version }}.
        echo "Output of Ref is: ${{github.ref}}"
    - name: Build Docker image
      shell: bash
      run: make app-image