name: Prepare Artifacts
on:
  workflow_run:
    workflows:
      - Testing
    types:
      - completed

jobs:
  # These images are created as it is prerequisite for the schema deployment via harness that every service should have an integration test yaml file generated as manifest into fabric-deployments repo
  push-images:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check sha
        id: check_sha
        run: |
          echo "REF is: ${GITHUB_REF#refs/*/}"
          echo "SHA is: ${{github.sha}}"
          if [[ "$(git tag --points-at ${{ github.sha }})" == v* ]]; then
            echo "::set-output name=is_tagged::true"
          fi
      - name: Get version
        if: steps.check_sha.outputs.is_tagged == 'true'
        id: get_version
        run: |
          tag=$(git tag --points-at ${{ github.sha }})
          echo "::set-output name=version::${tag##*$'\n'}"
  demo-reusable-step:
    runs-on: ubuntu-latest
    name: A demo workflow
    steps:
      - uses: actions/checkout@v2
      - id: foo
        uses: demo-gha-workflow/reuse@main
        with:
          version: ${GITHUB_REF#refs/*/}