name: Deploy
"on":
  push:
    tags:
      - v[0-9].[0-9]+.[0-9]+

jobs:
  wait-on-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Wait on tests
        uses: lewagon/wait-on-check-action@master
        with:
          ref: ${{ github.ref }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          check-name: 'Quality Gate'
          wait-interval: 10
          allowed-conclusions: success

  generate-manifests:
    runs-on: ubuntu-latest
    needs: wait-on-checks
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check sha
        id: check_sha
        run: |
          echo "Tag is: ${GITHUB_REF#refs/*/}"
          if [[ "$(git tag --points-at ${{ github.sha }})" == v* ]]; then
          echo "::set-output name=is_tagged::true"
          fi
      - name: Get version
        if: steps.check_sha.outputs.is_tagged == 'true'
        id: get_version
        run: |
          tag=$(git tag --points-at ${{ github.sha }})
          echo "::set-output name=version::${tag##*$'\n'}"