name: Deploy
# This is similar to deploy.yaml from statement-ingest used to manage release tags.
"on":
  push:
    tags:
      - "v[0-9].[0-9]+.[0-9]+"

jobs:
#  wait-for-check-name:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#
#      - name: Wait on tests
#        uses: lewagon/wait-on-check-action@master
#        with:
#          ref: ${{ github.ref }}
#          repo-token: ${{ secrets.GITHUB_TOKEN }}
#          running-workflow-name: wait-for-check-name
#          wait-interval: 10

  push-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Push Image
        uses: ./.github/workflows/composite-actions/push-images
        with:
          version: ${GITHUB_REF#refs/*/}

  flex-templates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build Flex Templates
        uses: ./.github/workflows/composite-actions/flex-template
        with:
          version: ${GITHUB_REF#refs/*/}

  generate-manifests:
    runs-on: ubuntu-latest
    needs: [push-images, flex-templates]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check sha
        id: check_sha
        run: |
          echo "Tag is: ${GITHUB_REF#refs/*/}"
          if [[ "$(git tag --points-at ${{ github.sha }})" == v* ]]; then
          echo "::set-output name=is_tagged::true"
          fi
      - name: Get version
        if: steps.check_sha.outputs.is_tagged == 'true'
        id: get_version
        run: |
          tag=$(git tag --points-at ${{ github.sha }})
          echo "::set-output name=version::${tag##*$'\n'}"