name: Deploy
# This is similar to deploy.yaml from statement-ingest used to manage release tags.
"on":
  push:
    tags:
      - "v[0-9].[0-9]+.[0-9]+"

jobs:
# https://github.com/marketplace/actions/wait-on-checkissues having issues waiting for checks in workflows to finish.
# Ex: https://github.com/syrils/demo-gha-workflow/runs/3785198041?check_suite_focus=true
  wait-for-check-name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Wait on tests
        uses: lewagon/wait-on-check-action@master
        with:
          ref: ${{ github.ref }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          check-name:  'wait-for-quality-gate'
          running-workflow-name: wait-for-check-name
          wait-interval: 10

  generate-manifests:
    runs-on: ubuntu-latest
#    needs: wait-for-check-name
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check sha
        id: check_sha
        run: |
          echo "Tag is: ${GITHUB_REF#refs/*/}"
          if [[ "$(git tag --points-at ${{ github.sha }})" == v* ]]; then
          echo "::set-output name=is_tagged::true"
          fi
      - name: Get version
        if: steps.check_sha.outputs.is_tagged == 'true'
        id: get_version
        run: |
          tag=$(git tag --points-at ${{ github.sha }})
          echo "::set-output name=version::${tag##*$'\n'}"

  flex-templates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build Flex Templates
        uses: ./.github/workflows/composite-actions/flex-template
        with:
          version: ${GITHUB_REF#refs/*/}