name: Init Checks
on:
  push:

jobs:
  bb-test:
    runs-on: ubuntu-latest
    if: ${{ !(startsWith(github.ref, 'refs/tags/') && endsWith(github.ref, '/docbox')) }}
    steps:
      - name: Sleep for few seconds
        run: sleep 30s
        shell: bash

#  quality-gate:
#    runs-on: ubuntu-latest
#    needs: [bb-test, test-coverage]
#    steps:
#      - name: Wait for checks
#        run: echo "All tests completed"
#        shell: bash

#  wait-for-quality-gate:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Wait for tests to succeed
#        uses: lewagon/wait-on-check-action@master
#        with:
#          ref: ${{ github.ref }}
#          running-workflow-name: wait-for-quality-gate
#          repo-token: ${{ secrets.GITHUB_TOKEN }}
#          wait-interval: 10
