name: Testing
on:
  push:

jobs:
  test-coverage:
    if: ${{ !(startsWith(github.ref, 'refs/tags/') && endsWith(github.ref, '/docbox')) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.13'
      - name: Checkout
        uses: actions/checkout@v2
      # Fetch all refs and full history for pull request analysis and blame information, respectively
      - run: git fetch --prune --unshallow

      - name: Unit Tests
        env:
          GOPROXY: "https://proxy.golang.org"
        run: |
          echo "Output of Ref is: ${{github.ref}}"
          echo "Output of SHA is: ${{github.sha}}"
          echo ${{ !startsWith(github.ref, 'refs/tags/*/docbox') }}
          echo ${{ !contains('refs/tags/*/docbox', github.ref) }}
          make test

  bb-test:
    runs-on: ubuntu-latest
    if: ${{ !(startsWith(github.ref, 'refs/tags/') && endsWith(github.ref, '/docbox')) }}
    steps:
      - name: Sleep for few seconds
        run: sleep 30s
        shell: bash

#  quality-gate:
#    runs-on: ubuntu-latest
#    needs: [bb-test, test-coverage]
#    steps:
#      - name: Wait for checks
#        run: echo "All tests completed"
#        shell: bash

#  wait-for-quality-gate:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Wait for tests to succeed
#        uses: lewagon/wait-on-check-action@master
#        with:
#          ref: ${{ github.ref }}
#          running-workflow-name: wait-for-quality-gate
#          repo-token: ${{ secrets.GITHUB_TOKEN }}
#          wait-interval: 10
