name: Testing
on:
  push:

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.13'
      - name: Checkout
        uses: actions/checkout@v2
      # Fetch all refs and full history for pull request analysis and blame information, respectively
      - run: git fetch --prune --unshallow

      - name: Unit Tests
        env:
          GOPROXY: "https://proxy.golang.org"
        run: |
          echo "Output of Ref is: ${{github.ref}}"
          echo "Output of SHA is: ${{github.sha}}"
          make test

  bb-test:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for few seconds
        run: sleep 45s
        shell: bash

  quality-gate:
    runs-on: ubuntu-latest
    needs: [test-coverage, bb-test]
    steps:
      - name: Wait for quality gate
        run: echo "All checks completed"
