name: Testing
on:
  push:

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.13'
      - name: Checkout
        uses: actions/checkout@v2
      # Fetch all refs and full history for pull request analysis and blame information, respectively
      - run: git fetch --prune --unshallow

      - name: Unit Tests
        env:
          GOPROXY: "https://proxy.golang.org"
        run: |
          echo "Output of Ref is: ${{github.ref}}"
          echo "Output of SHA is: ${{github.sha}}"
          make test

  bb-test:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for few seconds
        run: sleep 45s
        shell: bash

  quality-gate:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for other checks to succeed
        uses: lewagon/wait-on-check-action@v1.0.0
        with:
          ref: ${{ github.ref }}
          running-workflow-name: 'quality-gate'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
