name: Testing
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - 'hotfix/[0-9]+.[0-9]+.[0-9]+/**'
      - main
      - master
    tags:
      - v*.*.*

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'tags/*/stmt-') == false
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.13'
      - name: Checkout
        uses: actions/checkout@v2
      # Fetch all refs and full history for pull request analysis and blame information
      - run: git fetch --prune --unshallow

      - name: Unit Tests
        env:
          GOPROXY: "https://proxy.golang.org"
        run: make test
